mvc/Models/Bill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mvc.Models
{
    public class Bill
    {
		public int BillId { get; set; }
		[DataType(DataType.Date)]
		[Display(Name = "Ngày hóa đơn")]
		public DateTime Date { get; set; }

		[Required(ErrorMessage = "Vui lòng nhập họ tên.")]
		[Display(Name = "Tên khách hàng")]
		public string CustomerName { get; set; }

		[Required(ErrorMessage = "Vui lòng nhập số điện thoại.")]
		[Display(Name = "Điện thoại khách hàng")]
		public string CustomerPhone { get; set; }

		[Required(ErrorMessage = "Vui lòng nhập địa chỉ giao hàng.")]
		[Display(Name = "Địa chỉ khách hàng")]
		public string CustomerAddress { get; set; }

		[DisplayFormat(DataFormatString = "{0:#,##0} đ")]
		[Display(Name = "Tổng trị giá")]
		public int BillTotal { get; set; }

		public ICollection<BillDetail> BillDetails { get; set; }
	}
}

mvc/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc.Data;
using mvc.Models;
using OfficeOpenXml;
using Microsoft.AspNetCore.Http;

namespace mvc.Controllers
{
    public class BillsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BillsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Bills
        public async Task<IActionResult> Index()
        {
            return View(await _context.Bill.ToListAsync());
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .Include(b =>b.BillDetails).ThenInclude(b =>b.Product)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // GET: Bills/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillId,Date,CustomerName,CustomerPhone,CustomerAddress,BillTotal")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bill);
        }

        // GET: Bills/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BillId,Date,CustomerName,CustomerPhone,CustomerAddress,BillTotal")] Bill bill)
        {
            if (id != bill.BillId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillExists(bill.BillId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bill);
        }

        // GET: Bills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }
        public async Task<IActionResult> ExportToExcel()
        {
            var doctors = from m in _context.Bill
                          select m;

            byte[] fileContents;
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("DoctorsInfo");
            Sheet.Cells["A1"].Value = "Ngày hóa đơn";
            Sheet.Cells["B1"].Value = "Tên khách hàng";
            Sheet.Cells["C1"].Value = "Số điện thoại";
            Sheet.Cells["D1"].Value = "Địa chỉ";
            Sheet.Cells["E1"].Value = "Tổng trị giá";


            int row = 2;
            foreach (var item in doctors)
            {
                Sheet.Cells[string.Format("A{0}", row)].Value = item.Date;
                Sheet.Cells[string.Format("B{0}", row)].Value = item.CustomerName;
                Sheet.Cells[string.Format("C{0}", row)].Value = item.CustomerPhone;
                Sheet.Cells[string.Format("D{0}", row)].Value = item.CustomerAddress;
                Sheet.Cells[string.Format("E{0}", row)].Value = item.BillTotal;


                row++;
            }


            Sheet.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            fileContents = Ep.GetAsByteArray();

            if (fileContents == null || fileContents.Length == 0)
            {
                return NotFound();
            }

            return File(
                fileContents: fileContents,
                contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                fileDownloadName: "Danh sach hoa don.xlsx"
            );
        }
        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bill = await _context.Bill.FindAsync(id);
            _context.Bill.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillExists(int id)
        {
            return _context.Bill.Any(e => e.BillId == id);
        }
    }
}

mvc/Views/Bills/Create.cshtml
@model mvc.Models.Bill

@{
    ViewData["Title"] = "Thêm hóa đơn -";
}

<h1>Thêm</h1>

<h4>Hóa đơn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerAddress" class="control-label"></label>
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillTotal" class="control-label"></label>
                <input asp-for="BillTotal" class="form-control" />
                <span asp-validation-for="BillTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mvc/Views/Bills/Delete.cshtml
@model mvc.Models.Bill

@{
    ViewData["Title"] = "Xóa hóa đơn -";
}

<h1>Xóa</h1>

<h3>Bạn có chắc chắn muốn xóa hóa đơn?</h3>
<div>
    <h4>Hóa đơn</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BillTotal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BillTotal)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="BillId" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Trở về</a>
    </form>
</div>

mvc/Views/Bills/Details.cshtml
@model mvc.Models.Bill

@{
    ViewData["Title"] = "Thông tin hóa đơn -";
}

<h1>Xem thông tin</h1>

<div>
    <h4>Hóa đơn</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BillTotal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BillTotal)
        </dd>
        <dt class="col-sm-2">
            Thông tin chi tiết
        </dt>
        <dd class="col-sm-10">
            <table class="table table-bordered">
                <tr><th>Tên hàng</th><th>Đơn giá</th><th>Số lượng</th><th>Thành tiền</th></tr>
                @foreach (var i in Model.BillDetails)
                {
                    <tr>
                        <td>
                            <img src="~/images/@(i.Product.Image)" width="70" class="img-thumbnail" />""
                            @(i.Product.Name)
                        </td>
                        <td>@(i.Price)</td>
                        <td>@(i.Quantity)</td>
                        <td>@(i.Amount)</td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BillId">Chỉnh sửa</a> |
    <a asp-action="Index">Trở về</a>
</div>

mvc/Views/Bills/Edit.cshtml
@model mvc.Models.Bill

@{
    ViewData["Title"] = "Sửa hóa đơn -";
}

<h1>Sửa</h1>

<h4>Hóa đơn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BillId" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerAddress" class="control-label"></label>
                <input asp-for="CustomerAddress" class="form-control" />
                <span asp-validation-for="CustomerAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillTotal" class="control-label"></label>
                <input asp-for="BillTotal" class="form-control" />
                <span asp-validation-for="BillTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Chấp nhận" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mvc/Views/Bills/Index.cshtml
@model IEnumerable<mvc.Models.Bill>

@{
    ViewData["Title"] = "Hóa đơn -";
}

<h1>Danh sách các hóa đơn</h1>

<p>
    <a asp-action="Create">Thêm hóa đơn mới</a>
    <a class="text-right" style="overflow: hidden; padding: 1px 0px 0px 0px; margin-top: -47px; margin-bottom: 10px;">
        | <button type="button" class="btn btn-outline-info" onclick="location.href='@Url.Action("ExportToExcel", "Bills")'">Xuất danh sách các hóa đơn</button>
    </a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillTotal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerPhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BillTotal)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.BillId">Sửa</a> |
                    <a asp-action="Details" asp-route-id="@item.BillId">Xem</a> |
                    <a asp-action="Delete" asp-route-id="@item.BillId">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>