mvc/Models/BillDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace mvc.Models
{
    public class BillDetail
    {
		public int BillDetailId { get; set; }

		[Display(Name = "Chọn địa chỉ")]
		public int BillId { get; set; }
		[Display(Name = "Chọn sản phẩm")]
		public int ProductId { get; set; }
		[DisplayFormat(DataFormatString = "{0:#,##0} đ")]
		[Display(Name = "Giá")]
		public int Price { get; set; }

		[Display(Name = "Số lượng")]
		public int Quantity { get; set; }
		[DisplayFormat(DataFormatString = "{0:#,##0} đ")]
		[Display(Name = "Tổng trị giá")]
		public int Amount { get; set; }
		[Display(Name = "Địa chỉ")]
		public Bill Bill { get; set; }
		[Display(Name = "Tên sản phẩm")]
		public Product Product { get; set; }
	}
}

mvc/Controllers/BillDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{
    public class BillDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BillDetailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BillDetails
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BillDetail.Include(b => b.Bill).Include(b => b.Product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BillDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billDetail = await _context.BillDetail
                .Include(b => b.Bill)
                .Include(b => b.Product)
                .FirstOrDefaultAsync(m => m.BillDetailId == id);
            if (billDetail == null)
            {
                return NotFound();
            }

            return View(billDetail);
        }

        // GET: BillDetails/Create
        public IActionResult Create()
        {
            ViewData["BillId"] = new SelectList(_context.Bill, "BillId", "CustomerAddress");
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Name");
            return View();
        }

        // POST: BillDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillDetailId,BillId,ProductId,Price,Quantity,Amount")] BillDetail billDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(billDetail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BillId"] = new SelectList(_context.Bill, "BillId", "CustomerAddress", billDetail.BillId);
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Name", billDetail.ProductId);
            return View(billDetail);
        }

        // GET: BillDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billDetail = await _context.BillDetail.FindAsync(id);
            if (billDetail == null)
            {
                return NotFound();
            }
            ViewData["BillId"] = new SelectList(_context.Bill, "BillId", "CustomerAddress", billDetail.BillId);
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Name", billDetail.ProductId);
            return View(billDetail);
        }

        // POST: BillDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BillDetailId,BillId,ProductId,Price,Quantity,Amount")] BillDetail billDetail)
        {
            if (id != billDetail.BillDetailId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(billDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillDetailExists(billDetail.BillDetailId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BillId"] = new SelectList(_context.Bill, "BillId", "CustomerAddress", billDetail.BillId);
            ViewData["ProductId"] = new SelectList(_context.Product, "Id", "Name", billDetail.ProductId);
            return View(billDetail);
        }



        // GET: BillDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var billDetail = await _context.BillDetail
                .Include(b => b.Bill)
                .Include(b => b.Product)
                .FirstOrDefaultAsync(m => m.BillDetailId == id);
            if (billDetail == null)
            {
                return NotFound();
            }

            return View(billDetail);
        }

        // POST: BillDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var billDetail = await _context.BillDetail.FindAsync(id);
            _context.BillDetail.Remove(billDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillDetailExists(int id)
        {
            return _context.BillDetail.Any(e => e.BillDetailId == id);
        }
    }
}

mvc/Views/BillDetails/Create.cshtml
@model mvc.Models.BillDetail

@{
    ViewData["Title"] = "Thêm thông tin hóa đơn -";
}

<h1>Thêm</h1>

<h4>Thông tin hóa đơn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BillId" class="control-label"></label>
                <select asp-for="BillId" class="form-control" asp-items="ViewBag.BillId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Chấp nhận" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mvc/Views/BillDetails/Delete.cshtml
@model mvc.Models.BillDetail

@{
    ViewData["Title"] = "Xóa thông tin hóa đơn -";
}

<h4>Thông tin hóa đơn</h4>

<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bill)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bill.CustomerAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="BillDetailId" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Trở về</a>
    </form>
</div>

mvc/Views/BillDetails/Details.cshtml
@model mvc.Models.BillDetail

@{
    ViewData["Title"] = "Thông tin -";
}

<h4>Chi tiết hóa đơn</h4>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Bill)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bill.CustomerAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BillDetailId">Sửa</a> |
    <a asp-action="Index">Trở về</a>
</div>

mvc/Views/BillDetails/Edit.cshtml
@model mvc.Models.BillDetail

@{
    ViewData["Title"] = "Sửa";
}



<h4>Sửa hóa đơn</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BillDetailId" />
            <div class="form-group">
                <label asp-for="BillId" class="control-label"></label>
                <select asp-for="BillId" class="form-control" asp-items="ViewBag.BillId"></select>
                <span asp-validation-for="BillId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Chấp nhận" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

mvc/Views/BillDetails/Index.cshtml
@model IEnumerable<mvc.Models.BillDetail>

@{
    ViewData["Title"] = "Chi tiết hóa đơn ";
}

<h1>Thông tin chi tiết </h1>

<p>
    <a asp-action="Create">Thêm mới</a>
    <a class="text-right" style="overflow: hidden; padding: 1px 0px 0px 0px; margin-top: -47px; margin-bottom: 10px;">
        | <button type="button" class="btn btn-outline-info" onclick="location.href='@Url.Action("ExportToExcel", "BillDetails")'">Xuất thông tin hóa đơn</button>
    </a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bill.CustomerAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.BillDetailId">Sửa</a> |
                    <a asp-action="Details" asp-route-id="@item.BillDetailId">Xem</a> |
                    <a asp-action="Delete" asp-route-id="@item.BillDetailId">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>